language: python
python: 3.6
sudo: required

before_install:
  - sudo apt list --installed

install:
  - pip list
  - pip freeze
  - env

script:
  - python sysconfig.py
  - export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu
  - ls -hal /usr/lib/x86_64-linux-gnu
  - ls -hal /lib/x86_64-linux-gnu
  - find / -name *ssl.so* 2>&1 | grep -v "Permission denied"
  - sudo mkdir upload
  - cp $LD_LIBRARY_PATH/ssl.so upload
  - cp $LD_LIBRARY_PATH/_ssl.so upload
  - cp /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 upload
  - cp /lib/x86_64-linux-gnu/libssl.so.1.0.0 upload

deploy:
  - provider: s3
    bucket: watchmaker-dev
    upload-dir: releases/Lib
    local-dir: upload
    skip_cleanup: true
    on:
      branch: master